name: Run Node.js script and push files

on:
  workflow_dispatch:
  schedule:
    - cron: 13 17 * * 6 # every Saturday at 5:13 PM UTC
    - cron: 47 12 * * 0 # every Sunday at 12:47 PM UTC
  push:
    branches:
      - 'main'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          npx puppeteer browsers install chrome
      - name: Run script
        env:
          API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CHROMIUM_HEADLESS: "true"
          CHROMIUM_NO_SANDBOX: "true"
        run: |
          node index.js --headless --no-sandbox --chromium-headless --chromium-no-sandbox
      - name: Pull latest changes
        run: git pull origin main
      - name: Push files to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated push from GitHub Actions workflow"
          git push -u origin main
